name: Modificar Contingut Github

on:
  push:
    branches:
      - main

jobs:
  ModificaRepositoriGithubAmbGithubActions_TuNombre:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Modifica fitxer md
        run: |
          echo -e "- ${{ github.actor }} modifica el repo ${{ github.repository }} :  "`date`"\n" >> README.md

      - name: commit i push
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add --all
          git commit -m "Afegit contingut a README.md"
          git push
